baseURL = "https://blog.imoing.com/"
relativeURLs = true
languageCode = "zh-cn"
title = "番茄不爱吃西红柿"
theme = "hugo-paper"
hasCJKLanguage = true
summarylength = 30
enableEmoji = true

[taxonomies]
  tags   = "tags"
  category = "categories"
  series = "series"

[params]
title = "番茄不爱吃西红柿"
author = "Jake Guo"
description = "Jake"
profilePicture = "images/profile.jpg"
mainSections = ["post"]

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/cimoing"


## Menu items

[menu]
  [[menu.main]]
  name = "首页"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "文章"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "标签"
  weight = 300
  identifier = "tags"
  url = "/tags/"

  [[menu.main]]
  name = "分类"
  weight = 400
  identifier = "categories"
  url = "/categories/"
